# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  cursor: "#957FB8"
  error: "#E82424"
  git: "#98BB6C"
  info: "#DCA561"
  path: "#7E9CD8"
  ssh: "#957FB8"
  warn: "#FF9E3B"
transient_prompt:
  template: "❯ "
  background: transparent
  foreground_templates:
  - "{{if gt .Code 0}}p:error{{end}}"
  - "{{if eq .Code 0}}p:cursor{{end}}"
console_title_template: "{{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: "{{ if .SSHSession }}\ueba9 {{ .HostName }} {{ end }}"
    foreground: p:ssh
    background: transparent
    type: session
    style: plain
  - properties:
      cache_duration: none
      gitdir_format:  %s
      home_icon: "\uf015 "
      mapped_locations:
        ~/projects: "\ueac4 "
        ~/zintouch: "\uf32f "
      style: agnoster_full
    template: "{{.Path}}"
    foreground: p:path
    background: transparent
    type: path
    style: plain
  - properties:
      cache_duration: none
      commit_icon: "@"
      fetch_status: true
    template: " {{ .HEAD }} {{ if or (.Working.Changed) (.Staging.Changed) }}\uf044 {{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}"
    foreground: p:git
    background: transparent
    type: git
    style: plain
  newline: true
- type: prompt
  alignment: right
  overflow: hide
  segments:
  - properties:
      cache_duration: none
      threshold: 5000
    template:  {{ .FormattedMs }}
    foreground: p:warn
    background: transparent
    type: executiontime
    style: plain
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: ❯
    background: transparent
    type: text
    style: plain
    foreground_templates:
    - "{{if gt .Code 0}}p:error{{end}}"
    - "{{if eq .Code 0}}p:cursor{{end}}"
  newline: true
version: 3
final_space: true
