# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 2
final_space: true
console_title_template: "{{ .Folder }}"
blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: session
        style: plain
        foreground: p:ssh
        background: transparent
        template: "{{ if .SSHSession }} {{ .HostName }} {{ end }}"

      - type: path
        style: plain
        background: transparent
        foreground: p:path
        template: '{{.Path}}'
        properties:
          style: agnoster_full
          home_icon: ' '
          gitdir_format: ' %s'
          mapped_locations:
            "~/projects": " "
            "~/funatic": "󰫳"
            "~/boomerweb": "󰫯 "

      - type: git
        style: plain
        foreground: p:git
        background: transparent
        template: ' {{ .HEAD }} {{ if or (.Working.Changed) (.Staging.Changed) }} {{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'
        properties:
          commit_icon: '@'
          fetch_status: true

      - type: text
        style: plain
        foreground: p:info
        background: transparent
        templates:
          - ' {{ if .Env.VUE_APP_HOSPITAL }}󰋡 {{ .Env.VUE_APP_HOSPITAL }} {{ end }}'
          - '{{ if .Env.ECONSULT }}󰩂 e-consult {{ end }}'

  - type: prompt
    alignment: right
    overflow: hide
    segments:
      - type: executiontime
        style: plain
        foreground: p:warn
        background: transparent
        template: ' {{ .FormattedMs }}'
        properties:
          threshold: 5000

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: 'text'
        style: 'plain'
        foreground_templates:
          - "{{if gt .Code 0}}p:error{{end}}"
          - "{{if eq .Code 0}}p:cursor{{end}}"
        background: transparent
        template: '❯'
transient_prompt:
  foreground_templates:
    - "{{if gt .Code 0}}p:error{{end}}"
    - "{{if eq .Code 0}}p:cursor{{end}}"
  background: transparent
  template: '❯ '
palette:
  path: '#7E9CD8'
  error: '#E82424'
  cursor: '#957FB8'
  ssh: '#957FB8'
  git: '#98BB6C'
  warn: '#FF9E3B'
  info: '#DCA561'
